# ~/~ begin <<docs/index.md#entangled.toml>>[init]
version = "2.0"
watch_list = ["docs/*.md"]
hooks = ["quarto_attributes", "brei"]

# ~/~ begin <<docs/index.md#brei>>[init]
[brei]
include = ["docs/weave.toml", ".entangled/tasks.json"]
# ~/~ end
# ~/~ begin <<docs/index.md#brei>>[1]
[brei.runner.gnuplot]
command = "gnuplot"
args = ["${script}"]
# ~/~ end
# ~/~ begin <<docs/index.md#brei>>[2]
[[brei.call]]
template = "copy"
collect = "copy-figures"
[brei.call.args]
srcdir = "docs/fig"
tgtdir = "docs/site/fig"
basename = ["sine.svg"]

[[brei.call]]
template = "pandoc"
collect = "html"
[brei.call.args]
basename = ["index"]

[[brei.task]]
name = "weave"
requires = ["#html", "#static", "#copy-figures", "#data-products"]
# ~/~ end
# ~/~ begin <<docs/index.md#brei>>[3]
[[brei.task]]
description = "Obtain git commit id"
stdout = "var(commit)"
script = "git rev-parse --verify HEAD"

[[brei.task]]
description = "Create data output dir"
name = "output-prep"
script = """
mkdir -p data/${commit}
ln -sf ${commit} data/latest
"""

[brei.template.copy-from-data]
description = "copying `${pathname}`"
requires = ["data/${commit}/${pathname}"]
creates = ["docs/site/${pathname}"]
script = "cp data/${commit}/${pathname} docs/site/${pathname}"
# ~/~ end
# ~/~ begin <<docs/index.md#brei>>[4]
[[brei.call]]
template = "copy-from-data"
collect = "data-products"
[brei.call.args]
pathname = ["fig/brown-noise.svg"]
# ~/~ end
# ~/~ end